# Generated by Django 5.0.4 on 2024-05-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(null=True, upload_to='static/images/userpic/')),
                ('address', models.TextField()),
            ],
        ),
    ]
