# Generated by Django 5.0.4 on 2024-05-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=25, null=True)),
                ('Message', models.TextField(null=True)),
            ],
        ),
    ]
