# Generated by Django 5.0.4 on 2024-05-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
