# Generated by Django 5.0.4 on 2024-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
