# Generated by Django 5.0.4 on 2024-05-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_ticketbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketBooking',
        ),
    ]
