# Generated by Django 5.0.4 on 2024-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_ticketbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=50)),
                ('train_name', models.CharField(max_length=255)),
                ('available_seats_first_class', models.IntegerField(default=150)),
                ('available_seats_second_class', models.IntegerField(default=150)),
                ('available_seats_sleeper_class', models.IntegerField(default=150)),
            ],
        ),
        migrations.DeleteModel(
            name='TicketBooking',
        ),
    ]
