# Generated by Django 5.0.4 on 2024-05-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_railwaystation_delete_train'),
    ]

    operations = [
        migrations.RenameField(
            model_name='railwaystation',
            old_name='station_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='railwaystation',
            old_name='station_name',
            new_name='name',
        ),
    ]
