# Generated by Django 5.0.4 on 2024-05-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_station_code_railwaystation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='user.railwaystation')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='user.railwaystation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='user.ticket')),
            ],
        ),
    ]
