# Generated by Django 5.0.4 on 2024-05-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_ticket_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
