# Generated by Django 5.0.4 on 2024-05-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='station_from',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='station_to',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=50)),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='user.railwaystation')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='user.railwaystation')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='user.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
