# Generated by Django 5.0.4 on 2024-05-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_ticket_station_from_remove_ticket_station_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
    ]
