# Generated by Django 5.0.4 on 2024-05-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
