# Generated by Django 5.0.4 on 2024-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
