# Generated by Django 4.2.7 on 2024-05-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_booking_pnr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
