# Generated by Django 4.2.7 on 2024-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
